#!/usr/bin/env bash

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
	export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
else # macOS `ls`
	colorflag="-G"
	export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi


# List all files colorized in long format
alias l="ls -lF ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -laF ${colorflag}"

# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

# Always use color output for `ls`
alias ls="command ls -1 ${colorflag}"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Get week number
alias week='date +%V'

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# Get macOS Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm install npm -g; npm update -g; sudo gem update --system; sudo gem update; sudo gem cleanup'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# JavaScriptCore REPL
jscbin="/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc";
[ -e "${jscbin}" ] && alias jsc="${jscbin}";
unset jscbin;

# Trim new lines and copy to clipboard
alias c="tr -d '\n' | pbcopy"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Merge PDF files
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

# Disable Spotlight
alias spotoff="sudo mdutil -a -i off"
# Enable Spotlight
alias spoton="sudo mdutil -a -i on"

# PlistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias plistbuddy="/usr/libexec/PlistBuddy"

# Airport CLI alias
alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
# (useful when executing time-consuming commands)
alias badge="tput bel"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
	alias "$method"="lwp-request -m '$method'"
done

# Make Grunt print stack traces by default
command -v grunt > /dev/null && alias grunt="grunt --stack"

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume output volume 100'"

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

#=============================================================================
#=============================================================================
source ~/.git-aliases.bash;

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd ..&& ls -1"
alias ...="cd ../.. && ls -1"
alias ....="cd ../../.. && ls -1"
alias .....="cd ../../../.. && ls -1"
alias -- -="cd -"

#========== Docker Shortcuts =============
dkr_aliases(){
    image_tag=$1
    container_info=$(docker ps | grep $image_tag)

    alias dps="docker ps | grep ${container_info:0:12}"
    alias dstp="docker stop ${container_info:0:12}"
    alias dbld="""docker build -t "${image_tag}""""
    alias dlg="docker logs --follow ${container_info:0:12}"
    alias dx="docker exec -it ${container_info:0:12} bash"
}
#=========================================

alias chrome="open -na 'Google Chrome' --args --new-window"
alias bu="code $HOME/.bash_utils.bash"
alias bp="code $HOME/.bash_profile"
alias aliases="code $HOME/.aliases"

alias startmysql="sudo /usr/local/mysql/support-files/mysql.server start"
alias stopmysql="sudo /usr/local/mysql/support-files/mysql.server stop"
alias statusmysql="sudo /usr/local/mysql/support-files/mysql.server status"
alias logmysql="sudo tail -f /usr/local/mysql/data/$(hostname).err"


# NOTES & BOOKS of various Development Tools.

alias ntpdf="open $NTHUB/nts && open $NTHUB/PDFs"
alias nthub="cd $NTHUB"
alias ntabc="code $NTHUB/nts/notes_arabic.md"
alias ntbash="code $NTHUB/nts/notes_bash.md"
alias ntdb="code $NTHUB/nts/notes_db.md"
alias ntwdev="code $NTHUB/nts/notes_web_developement.md"
alias ntshell="code $NTHUB/nts/notes_shell.md"
alias ntlnx="code $NTHUB/nts/notes_linux.md"
alias ntgcp="code $NTHUB/nts/notes_gcp.md"
alias ntfw="code $NTHUB/nts/notes_fw.md"
alias ntmd="code $NTHUB/nts/notes_md.md"
alias ntaws="code $NTHUB/nts/notes_aws.md"
alias ntdjango="code $NTHUB/nts/notes_django.md"
alias ntre="code $NTHUB/nts/notes_re.md"
alias ntml="code $NTHUB/nts/notes_msl.md"
alias ntrgh="code $HOME/notes_rough.md"
alias ntnsql="code $NTHUB/nts/notes_nosql.md"
alias ntprogterm="code $NTHUB/nts/notes_prog_terms.md"
alias ntyml="code $NTHUB/nts/notes_yml.md"
alias ntrmp="code $NTHUB/nts/notes_rmp.md"
alias ntgit="code $NTHUB/nts/notes_git.md"
alias ntdkr="code $NTHUB/nts/notes_docker.md"
alias ntaf="code $NTHUB/nts/notes_airflow.md"
alias ntvim="code $NTHUB/nts/notes_vim.md"
alias ntvsc="code $NTHUB/nts/notes_vscode.md"
alias ntmac="code $NTHUB/nts/notes_mac.md"
alias ntpy="code $NTHUB/nts/notes_py.md"
alias ntpytest="code $NTHUB/nts/notes_pytest.md"
alias nteng="open /Users/a.momin/gd/Writing\ English/Notes_English.gsheet"
alias ntflask="code $NTHUB/nts/notes_flask.md"
alias ntfastapi="code $NTHUB/nts/notes_fastapi.md"
alias ntjira="code $NTHUB/nts/notes_jira.md"
alias ntcss="open $NTHUB/nts/notes_css.gdoc"
alias nthtml="open $NTHUB/nts/notes_html.gdoc"
alias ntjnb="code $NTHUB/nts/notes_jnb.md"
alias ntfintech="code $NTHUB/nts/notes_fintech.md"
alias ntscicd="code $NTHUB/nts/notes_cicd.md"
alias ntstat="code $NTHUB/nts/notes_statistics.md"
alias ntnosql="code $NTHUB/nts/notes_nosql.md"

alias passdb="open $HOME/mydocs/gd/passdb.gsheet"
alias resume="open $HOME/mydocs/gd/jobs/resumes/A.Momin-pydev.docx"
alias jobdb="open $HOME/mydocs/gd/jobs/Jobs_DB.gsheet"
alias cmdnpm="code $NTHUB/nts/cmd_npm.txt"
alias cmdreact="code $NTHUB/nts/cmd_react.txt"
alias cmdcpp="code $NTHUB/nts/cmd_cpp.txt"

alias nbstat="jupyter notebook $NTHUB/nbs/statistics.ipynb"
alias nbepp="jupyter notebook $NTHUB/nbs/nt_epp.ipynb"
alias nbml="jupyter notebook $NTHUB/nbs/nt_ml.ipynb"
alias nbpd="jupyter notebook $NTHUB/nbs/nt_pd.ipynb"
alias nbplt="jupyter notebook $NTHUB/nbs/nt_plt.ipynb"
alias nbnp="jupyter notebook $NTHUB/nbs/nt_np.ipynb"
alias nbtorch="jupyter notebook $NTHUB/nbs/nt_torch.ipynb"


# alias fastai="cd $HOME/mydocs/Software_Development/Machine_Learning/fastai && conda activate fastai && jupyter notebook"
alias ae="deactivate &> /dev/null; source .venv/bin/activate"
alias cae="conda activate $1"
alias de="deactivate"
alias cde="conda deactivate"

alias bigdata="cd $HOME/mydocs/Software_Development/Big_Data && open ."
alias books="cd $HOME/mydocs/BOOKS/PDF\ Books && ls -1"
alias jlb="jupyter-lab"
alias jnb="jupyter notebook"
alias mlcourses="cd $HOME/mydocs/Software_Development/Machine_Learning/ml_courses && ls -1"
alias ml="cd $HOME/mydocs/Software_Development/Machine_Learning && ls -1"                 # ml ==> Machine_Learning

# alias ads="cd $HOME/mydocs/Software_Development/Algorithms_and_Data_Structures && deactivate &> /dev/null; source .venv/bin/activate"
alias ads="cd $HOME/mydocs/Software_Development/Algorithms_and_Data_Structures"
alias epi="cd $HOME/mydocs/Software_Development/Python_Program/Python3/elements-of-programming-interview && deactivate &> /dev/null; source .venv/bin/activate"
alias pp="cd $HOME/mydocs/Software_Development/Python_Program && ls -1"                   # pp ==> Python Program
alias pp2="cd $HOME/mydocs/Software_Development/Python_Program/Python2 && ls -1"          # pp2 ==> Python2 Program
alias pp3="cd $HOME/mydocs/Software_Development/Python_Program/Python3 && ls -1"          # pp3 ==> Python3 Program
alias bp="cd $HOME/mydocs/Software_Development/notes_hub/bash_scripting && ls -1"          # bp ==> Bash Program
alias jp="cd $HOME/mydocs/Software_Development/JavaPragrams && ls -1"                     # cpp ==> C++ Programs
alias jsp="cd $HOME/mydocs/Software_Development/Web_Development/Javascript_Program && ls -1"                         # pp3 ==> Python3 Program
alias cpp="cd $HOME/mydocs/Software_Development/C++_Programs && ls -1"                    # cpp ==> C++ Programs
alias algs4="cd $HOME/mydocs/Software_Development/algs4/src/main/java/edu/princeton/cs/algs4"
alias db="cd $HOME/mydocs/Software_Development/Databases && ls -1"               # sql ==> MySQL Program

alias mydocs="cd $HOME/mydocs && ls -1"
alias gd="cd $HOME/mydocs/gd && ls -1"
alias sd="cd $HOME/mydocs/Software_Development && ls -1"
alias wd="cd $HOME/mydocs/Software_Development/Web_Development && ls -1"

# Shortcuts
alias dl="cd ~/Downloads && ls -1"
alias dt="cd ~/Desktop && ls -1"
